[package]
name = "trashexpiry"
version = "0.1.0"
license = "MIT"
description = "Delete files that have been in Linux trash for 60 days."
authors = ["Thomas Kluyver <thomas@kluyver.me.uk>"]

[dependencies]
rust-ini = "0.10.0"
chrono = "0.4"
clap = "2.27"
xdg = "^2.1"
